### ISSUE TITLE
yugabyte sink connector fails with "Invalid schema for value STRUCT expected a map"

### ISSUE THREAD

**Issue by shashiy007** [yugabyte/yb-kafka-connector#13]
Im testing the yugabyte sink connector with protocol buffer. Wrote some messages using kafka-protobuf-console-producer and was able to consume them with kafka-protobuf-console-consumer. 

But the yugabyte sink connector fails with the following trace. 

[INFO] 2021-07-16 21:06:55,852 [task-thread-YBSink-PB-1-0] com.yb.connect.sink.YBSinkTask getStatements - Insert INSERT INTO demo.test_policy(policynumber,policydetails,policyprice) VALUES (?,?,?)
[INFO] 2021-07-16 21:06:55,852 [task-thread-YBSink-PB-1-0] com.yb.connect.sink.YBSinkTask getStatements - Prepare SinkRecord{kafkaOffset=0, timestampType=CreateTime} ConnectRecord{topic='pb-test', kafkaPartition=0, key=null, keySchema=null, value=Struct{policyNumber=100,policyPrice=2000.75,policyDetails=Auto Policy with two cars}, valueSchema=Schema{value_protobuf_test:STRUCT}, timestamp=1626469008552, headers=ConnectHeaders(headers=)} Key/Schema=null/null Value/Schema=Struct{policyNumber=100,policyPrice=2000.75,policyDetails=Auto Policy with two cars}/Schema{value_protobuf_test:STRUCT}
[ERROR] 2021-07-16 21:06:55,852 [task-thread-YBSink-PB-1-0] org.apache.kafka.connect.runtime.WorkerSinkTask deliverMessages - WorkerSinkTask{id=YBSink-PB-1-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. **Error: Invalid schema for value STRUCT expected a map.**
java.lang.IllegalArgumentException: Invalid schema for value STRUCT expected a map.
	at com.yb.connect.sink.YBSinkTask.getStatements(YBSinkTask.java:454)
	at com.yb.connect.sink.YBSinkTask.put(YBSinkTask.java:96)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Connector Properties:

{
  "name": "YBSink-PB-0",
  "config": {
    "connector.class": "com.yb.connect.sink.YBSinkConnector",
    "tasks.max": "1",
    "value.converter": "io.confluent.connect.protobuf.ProtobufConverter",
    "topics": "protobuf-test",
    "yugabyte.cql.tablename": "test_policy",
    "schema.registry.url": "http://schemaregistry:8081",
    "value.converter.schema.registry.url": "http://schemaregistry:8081",
    "yugabyte.cql.contact.points": "yb-tserver:9042",
    "yugabyte.cql.keyspace": "demo"
  }
}

**Comment by dubeyaditya6232** [comment]
I too got this kind of issue, i was using oracle source connector and jdbc sink connector,
after i added the config of key.deserializer to byteArrayDeserializer the issue got resolved.
