### ISSUE TITLE
Guava 19 conflict in cassandra-driver-core-3.2.0-yb-18.jar

### ISSUE THREAD

**Issue by ybnelson** [yugabyte/yb-kafka-connector#6]
Having to use cassandra-driver-core-3.2.0-yb-18.jar results in following error when trying to load Sink:
2019-12-28 01:05:19,706] INFO [Consumer clientId=connector-consumer-yugabyte-sink-0, groupId=connect-yugabyte-sink] Subscribed to topic(s): test_topic (org.apache.kafka.clients.consumer.KafkaConsumer:964)
[2019-12-28 01:05:19,711] INFO Start with keyspace=demo, table=test_table (com.yb.connect.sink.YBSinkTask:79)
[2019-12-28 01:05:19,784] INFO Detected Guava < 19 in the classpath, using legacy compatibility layer (com.datastax.driver.core.GuavaCompatibility:135)
[2019-12-28 01:05:19,792] ERROR WorkerSinkTask{id=yugabyte-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback
  at com.datastax.driver.core.GuavaCompatibility.selectImplementation(GuavaCompatibility.java:136)
  at com.datastax.driver.core.GuavaCompatibility.<clinit>(GuavaCompatibility.java:52)
  at com.datastax.driver.core.Cluster.<clinit>(Cluster.java:69)
  at com.yb.connect.sink.YBSinkTask.createCassandraClient(YBSinkTask.java:172)
  at com.yb.connect.sink.YBSinkTask.getCassandraSession(YBSinkTask.java:162)
  at com.yb.connect.sink.YBSinkTask.start(YBSinkTask.java:82)
  at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:300)
  at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
  at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
  at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.FutureFallback
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  ... 15 more
[2019-12-28 01:05:19,797] ERROR WorkerSinkTask{id=yugabyte-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)

**Comment by yasha-dev1** [comment]
I had the same issue with my application. the problem is the incompatibility of Guava. my application was with Play framework which at the time of writing this uses:
"com.google.guava" % "guava" % "28.2-jre"
but datastax has support only from Guava 19.0 to 25.1 (at the time of writing this)

so issue was solved by overriding the Guava version to 25.1: (in build.sbt)
dependencyOverrides += "com.google.guava" % "guava" % "25.1-jre"
